# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('update_time', models.DateTimeField()),
                ('expires_in', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Wechat Access Token',
                'db_table': 'wechat_access_token',
            },
        ),
    ]
