# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_list', models.TextField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Wechat Address List',
                'db_table': 'wechat_address_list',
            },
        ),
    ]
